media: images

content:

  - name: site
    label: サイト基本情報
    type: file
    path: content/site.json

  - name: menu
    label: メニュー
    type: collection
    path: content/menu
    fields:

      - name: name
        label: メニュー名
        type: string

      - name: price
        label: 料金
        type: string

      - name: description
        label: 説明
        type: text
